class RawData():
    def __init__(self):
        self.teacher_data = [["Albert Einstein", "xyz@gmail.com", "abc@college", "12345"],
                             ["Anne Sullivan", "xyz@gmail.com", "abc@college", "12345"],
                             ["Aristotle", "xyz@gmail.com", "abc@college", "12345"],
                             ["C.S. Lewis", "xyz@gmail.com", "abc@college", "12345"],
                             ["Christa McAuliffe", "xyz@gmail.com", "abc@college", "12345"],
                             ["Erin Gruwell", "xyz@gmail.com", "abc@college", "12345"],
                             ["Frederick Douglass", "xyz@gmail.com", "abc@college", "12345"],
                             ["Friedrich Froebel", "xyz@gmail.com", "abc@college", "12345"],
                             ["Gabriela Mistral", "xyz@gmail.com", "abc@college", "12345"],
                             ["Hanan al-Hroub", "xyz@gmail.com", "abc@college", "12345"]]

        self.course_data = [["BCA", 3],
                            ["MCA", 2],
                            ["BBA", 3],
                            ["MBA", 2],
                            ["MSC", 2],
                            ["B.COM", 3],
                            ["M.COM", 2]]

        self.subject_data = [["C Programming Language", "1", 2, 2],
                             ["FOC", "1", 2, 3],
                             ["C++", "2", 2, 4],
                             ["Java", "2", 2, 5],
                             ["Operating System", "3", 2, 6],
                             ["RDBMS", "3", 2, 7],
                             ["Dot Net", "3", 2, 6],
                             ["Mobile Computing", "3", 2, 7],
                             ["Computer Architecture", "1", 3, 8],
                             ["Computer Networking", "1", 3, 9],
                             ["Principles of Management", "1", 4, 10],
                             ["Business Mathematics & Statistics", "1", 4, 11],
                             ["Human Resource Management", "1", 5, 8],
                             ["Marketing Research", "1", 5, 9],
                             ["Pharmacy", "1", 6, 7],
                             ["Accountancy", "1", 7, 10],
                             ["Managerial Economics", "1", 8, 11]]

        self.student_data = [["aryaid101", "Ram", "Sharma", "xyz", "abc", "male", "22-07-2002", "xxxxxxxxxx", "fhg@gmail.com", "1", "BCA", "admin"],
                             ["aryaid102", "Sham", "jadeja", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "1", 2, "admin"],
                             ["aryaid103", "Sohan", "Sharma", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "2", 2, "admin"],
                             ["aryaid104", "Gaurav", "jadeja", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "2", 2, "admin"],
                             ["aryaid105", "Mayur", "Sharma", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "3", 2, "admin"],
                             ["aryaid106", "Aakash", "saraswat", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "3", 2, "admin"],
                             ["aryaid201", "Pradeep", "Sharma", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "1", 3, "admin"],
                             ["aryaid202", "honey", "saraswat", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "1", 3, "admin"],
                             ["aryaid301", "Hitesh", "Sharma", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "1", 4, "admin"],
                             ["aryaid302", "Vishwjeet", "Rawat", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "1", 4, "admin"],
                             ["aryaid401", "Suresh", "Sharma", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "1", 5, "admin"],
                             ["aryaid402", "Deepak", "Rawat", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "1", 5, "admin"],
                             ["aryaid501", "prashant", "Sharma", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "1", 6, "admin"],
                             ["aryaid502", "mayank", "singh", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "1", 6, "admin"],
                             ["aryaid601", "Davesh", "Sharma", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "1", 7, "admin"],
                             ["aryaid602", "Naman", "singh", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "1", 7, "admin"],
                             ["aryaid701", "Aman", "Sharma", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "1", 8, "admin"],
                             ["aryaid702", "Saahil", "Arora", "xyz", "abc", "male", "xx/xx/xxxx", "xxxxxxxxxx", "fhg@gmail.com", "1", 8, "admin"]]
